name: Linux

on:
  push:
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install zsh
      run: |
        apt-get update
        apt-get install -y zsh
    - name: Run test
      run: |
        zsh test/test.zsh
